name: Check
on:
  workflow_call:
    inputs:
      APP_NAME:
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      RELAY_GITHUB_TOKEN:
        required: true
      RELAY_SLACK_WEBHOOK_URL:
        required: true
jobs:
  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check lint
        run: yarn lint

      - name: Notify to Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: '${{ inputs.APP_NAME }} lint 結果'
          job_name: Check lint
          fields: repo, commit, author, job, took, eventName, workflow, pullRequest
        env:
          GITHUB_TOKEN: ${{ secrets.RELAY_GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.RELAY_SLACK_WEBHOOK_URL }}
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Comment to PR
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github_token: ${{ secrets.RELAY_GITHUB_TOKEN }}
          test-script: yarn test
          package-manager: yarn

      - name: Notify to Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: '${{ inputs.APP_NAME }} test 結果'
          job_name: Run test
          fields: repo, commit, author, job, took, eventName, workflow, pullRequest
        env:
          GITHUB_TOKEN: ${{ secrets.RELAY_GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.RELAY_SLACK_WEBHOOK_URL }}
