name: Develop Check & Deploy
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
jobs:
  check:
    uses: ./.github/workflows/check.yaml
    if: ${{ github.event_name == 'pull_request' }}
    secrets:
      RELAY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELAY_SLACK_WEBHOOK_URL: ${{ secrets.ORG_SLACK_WEBHOOK_URL }}
  dryrun:
    uses: ./.github/workflows/deploy.yaml
    if: ${{ github.event_name == 'pull_request' }}
    with:
      ENV_NAME: dev
      IS_DRY_RUN: true
    secrets:
      RELAY_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      RELAY_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      RELAY_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEV }}
      RELAY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELAY_SLACK_WEBHOOK_URL: ${{ secrets.ORG_SLACK_WEBHOOK_URL }}
  deploy:
    uses: ./.github/workflows/deploy.yaml
    if: ${{ github.event_name == 'push' }}
    with:
      ENV_NAME: dev
    secrets:
      RELAY_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      RELAY_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      RELAY_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEV }}
      RELAY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELAY_SLACK_WEBHOOK_URL: ${{ secrets.ORG_SLACK_WEBHOOK_URL }}
  release:
    uses: ./.github/workflows/git-pr-release.yaml
    if: ${{ github.event_name == 'push' }}
    with:
      FROM_BRANCH: develop
      TO_BRANCH: staging
    secrets:
      RELAY_APP_ID: ${{ secrets.CI_SYSTEM_APP_ID }}
      RELAY_PRIVATE_KEY: ${{ secrets.CI_SYSTEM_PRIVATE_KEY }}
  backlog:
    uses: ./.github/workflows/backlog.yaml
    if: ${{ github.event_name == 'push' }}
    with:
      PROJECT_KEY: SKILLUP
    secrets:
      RELAY_BACKLOG_API_KEY: ${{ secrets.BACKLOG_API }}
